```yaml
name: Android GUI Emulator

on:
  workflow_dispatch:   # run manually from GitHub Actions tab

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install base packages
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget git curl \
            qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils \
            virt-manager expect xvfb xfce4 xfce4-goodies x11vnc novnc websockify

      # Install Android SDK
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdtools.zip
          unzip cmdtools.zip -d cmdline-tools
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
          yes | cmdline-tools/latest/bin/sdkmanager --licenses
          cmdline-tools/latest/bin/sdkmanager --update
          cmdline-tools/latest/bin/sdkmanager "platform-tools" "emulator" "system-images;android-30;default;x86_64"

      # Create emulator
      - name: Create AVD
        run: |
          echo "no" | $HOME/android-sdk/cmdline-tools/latest/bin/avdmanager create avd \
            -n test -k "system-images;android-30;default;x86_64" --force

      # Start virtual display + emulator + VNC + noVNC
      - name: Start Emulator with noVNC
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$PATH

          # Start Xvfb (virtual display)
          Xvfb :0 -screen 0 1280x800x16 &
          export DISPLAY=:0

          # Start Android Emulator in background
          nohup emulator -avd test -no-snapshot -noaudio -no-boot-anim -gpu swiftshader_indirect &

          # Wait a bit for emulator boot
          sleep 30

          # Start x11vnc server
          x11vnc -display :0 -nopw -forever -shared -rfbport 5900 &

          # Start noVNC server (websocket proxy to VNC)
          websockify --web=/usr/share/novnc/ 6080 localhost:5900 &

          echo "Emulator is booting... Access GUI at:"
          echo "👉 http://<runner-public-ip>:6080/vnc.html"
```
