name: macos-remote-via-ngrok

on: [push, workflow_dispatch]

jobs:
remote:
runs-on: macos-latest
timeout-minutes: 120

steps:
- name: Checkout
  uses: actions/checkout@v4

- name: Install Homebrew (if missing)
  run: |
    if ! command -v brew >/dev/null 2>&1; then
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      if [ -d /opt/homebrew/bin ]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
      else
        eval "$(/usr/local/bin/brew shellenv)" || true
      fi
    fi

- name: Install TigerVNC & ngrok
  run: |
    brew update || true
    brew install tigervnc || true
    brew install --cask ngrok || brew install ngrok || true

- name: Configure VNC password
  env:
    VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
  run: |
    if [ -z "${VNC_PASSWORD:-}" ]; then
      echo "Missing VNC_PASSWORD secret" >&2; exit 1
    fi
    mkdir -p ~/.vnc
    printf "%s\n%s\n" "${VNC_PASSWORD}" "${VNC_PASSWORD}" | vncpasswd -f > ~/.vnc/passwd
    chmod 600 ~/.vnc/passwd

- name: Start VNC server
  run: |
    vncserver -kill :1 >/dev/null 2>&1 || true
    vncserver :1 -geometry 1280x800 -depth 24 || true
    sleep 2

- name: Auth ngrok & start TCP tunnel
  env:
    NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
  run: |
    if [ -z "${NGROK_AUTH_TOKEN:-}" ]; then
      echo "Missing NGROK_AUTH_TOKEN secret" >&2; exit 1
    fi
    ngrok authtoken "${NGROK_AUTH_TOKEN}" || true
    nohup ngrok tcp 5901 --log=stdout > ngrok.log 2>&1 &
    for i in 1 2 3 4 5 6 7 8 9 10; do sleep 1; curl -s http://127.0.0.1:4040/api/tunnels | grep -q '"proto":"tcp"' && break || true; done
    curl -s http://127.0.0.1:4040/api/tunnels | python3 - <<'PY'
```

import sys, json
s=sys.stdin.read()
try:
j=json.loads(s or '{}')
for t in j.get('tunnels', []):
if t.get('proto') == 'tcp':
print(t.get('public_url'))
break
except:
pass
PY
echo "" >> "$GITHUB_STEP_SUMMARY"
echo "- VNC (ngrok): see workflow log above" >> "$GITHUB_STEP_SUMMARY"
echo "- VNC password stored in secret VNC_PASSWORD" >> "$GITHUB_STEP_SUMMARY"

```
- name: Keep job alive
  run: |
    tail -f ngrok.log & sleep 7200 || true
```
