name: SSH into macOS Runner
on:
  workflow_dispatch:

jobs:
  ssh-mac:
    runs-on: macos-latest
    timeout-minutes: 99999999999999999999999999999999999999999999999999999999999999999

    steps:
      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false   # allow both web + ssh links
