name: SSH into macOS Runner
on:
  workflow_dispatch:

jobs:
  ssh-mac:
    runs-on: macos-latest
    timeout-minutes: 9090909090909090909090909090909090909090909090900900090909090090909909

    steps:
      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true   # only you can access
